# Generated by Django 5.0.3 on 2024-05-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
    ]
