# Generated by Django 5.0.4 on 2024-05-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
    ]
