# Generated by Django 5.0.4 on 2024-05-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='county',
            field=models.CharField(default='county', max_length=200),
            preserve_default=False,
        ),
    ]
